doc-warnings: false
test-warnings: false
strictness: veryhigh
max-line-length: 120
autodetect: true
ignore-paths:
  - example
python-stargets:
  - 2
  - 3
pylint:
  disable:
    - redefined-builtin
mccabe:
  run: true
dodgy:
  run: true
pyroma:
  run: true
